---
title: "inspect"
author: "Konner Macias"
date: "May 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What data do I want?
# - I would like perGame and advStats for each player in 2015
# - the salary of that player for 2015

```{r}
perGame <- read.csv("../data/player-data-wrangled/player2015/PerGame-2015wrangled.csv", stringsAsFactors = FALSE)

advStats <- read.csv("../data/player-data-wrangled/player2015/Adv-2015wrangled.csv", stringsAsFactors = FALSE)
```
Merge the data frames
```{r}
pgAdv <- merge(perGame, advStats, by = c("Player","Pos","G","Tm","Age","fix"))
pgAdv <- pgAdv[-c(7,8,33,34,48,53)]
colnames(pgAdv)
```
```{r}
summary(pgAdv)
```

# Get Player data
```{r}
fAgents <- read.csv('../data/salary-data/fixed-fa-signings/fixed-2015.csv', stringsAsFactors = FALSE)
fAgents <- fAgents[-c(1,2,3,4,5,6,7)]
colnames(fAgents)
```
# Merge into final data frame
```{r}
mega <- merge(pgAdv, fAgents, by.x = "fix", by.y ="name")
mega <- mega[-c(1,2,3,5)]
mega[is.na(mega)] <- 0
colnames(mega)
```
```{r}
library(ggplot2)
library(GGally)
library(corrplot)
M <- cor(mega)
corrplot(M,method = "color", type = "upper")
```
# Noteworthy variables:
GS, MP.x, FG, FGA, FG., X2P, X2PA, FT, FTA, ORB, DRB, TRB, STL, PS.G, MP.y, OWS, DWS, WS, BPM, VORP

# Now let's look at only those
```{r}
M <- cor(mega[c(3,4,5,6,7,11,12,15,16,18,19,20,22,26,27,40,41,42,46,47,49)])
corrplot.mixed(M, lower = "number", upper = "circle")
```


